[workspace]
[package]
name = "groth-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]

sp1-zkvm = { git = "https://github.com/succinctlabs/sp1", branch = "dev" }
sp1-verifier = { git = "https://github.com/succinctlabs/sp1", branch = "dev" }



[features]
risc0 = []
sp1 = []
